# CONSTANTS
CLIENT_ROOT_PATH   = "~/.p2pclient/"
CLIENT_SOCKET_PATH = "~/.p2pclient/uds_socket"


# CENTRAL SERVER HOST AND PORT
CENTRAL_SERVER_URL  = "127.0.0.1" 
CENTRAL_SERVER_PORT = 3000

# CENTRAL SERVER API
GET_ALL_FILES = "/files"
GET_FILE      = "/file/:filename"

# PEERING CONSTANTS
M_EXPONENT = 10

PEER_PORT = 8818
PEER_ADDR = "127.0.0.1" 



